# Modify if you use a different port...
ports:
- port: 9081
  visibility: public
tasks:
  - init: mvn install -DskipTests=false
  # Modify if you use a different local overlay folder
  - init: mkdir /tmp/data && chmod 777 /tmp/data 
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-maven